setwd("power")
dataset<- read.table("household_power_consumption.txt", sep=";", header=TRUE, colClasses="character")
dataset$Date <- as.Date(dataset$Date, format="%d/%m/%Y")
dataset$Time <- strptime(dataset$Time, format="%H:%M:%S")
dataset$Date<- as.numeric(dataset$Date)
dataset <- subset(dataset, Date==13545 |Date==13546)
dataset$Global_active_power<- as.numeric(dataset$Global_active_power)

plot(dataset$Global_active_power, type="l", xaxt="n", ylab="Global Active Power (kilowatts)", xlab="", cex.axis=0.8, cex.lab=0.7)
axlabels<- c("Thu", "Fri", "Sat")
axcoord<-c(1,1440,2880)
axis(1, at=axcoord, labels=axlabels)
dev.copy(png, file="plot2.png")
dev.off()
